### ISSUE TITLE
`save_to_file` not respecting config

### ISSUE THREAD

**Issue by carltongibson** [isaacbernat/pycrastinate#3]
Hiya, 

I'm just getting started with pycrastinate, so maybe I'll resolve this but it looks to me as if config values are not being respected. 

```
    "save_to_file": {
        "path": "./",
        "filename": "report.txt",
        "overwrite": True,
    },
```

Leads to:

```
  File "/Users/carlton/Documents/pycrastinate/modules/save_to_file.py", line 10, in save_to_file
    raise Exception("'{}' already exists".format(filename))
Exception: 'report.txt' already exists
```

I'm also not having any luck moving the save location by setting `path`. 

I'll look into this later — I'm enjoying the early progress for now :-) — but I wanted to get this down.

**Comment by isaacbernat** [comment]
@carltongibson sorry for not having looked into this as much as I should. Not long after creating pycrastinate we completely dropped the old codebase that had TODOs. All other places I've worked at forbade from even writing TODOs in the codebase using linter or were discouraged in favour of external tools. This meant I would not use this myself and therefore was hard to keep it up to date. Sorry for the inconvenience and thanks for having tried it.

**Comment by carltongibson** [comment]
Hi @isaacbernat no problem! It was handy for me for a period. I moved on too in the end and was just clearing up my lists. 

Thanks for your work!
