### ISSUE TITLE
Encoding errors

### ISSUE THREAD

**Issue by carltongibson** [isaacbernat/pycrastinate#4]
Running under Python 2 I ran into a UnicodeEncodeError in `process_result`:

```
...
2015-07-16 11:24:38.458050 finish pycrastinate module: save_to_file
2015-07-16 11:24:38.458059 start  pycrastinate module: process_results
Traceback (most recent call last):
  File "/Users/carlton/bin/pycrastinate.py", line 22, in <module>
    pycrastinate(sys.argv[1])
  File "/Users/carlton/bin/pycrastinate.py", line 18, in pycrastinate
    return run(_cfg.pipeline, _cfg.data, _cfg.enclose)
  File "/Users/carlton/bin/pycrastinate.py", line 10, in run
    OrderedDict(sorted(pipeline.items())).values(), [])
  File "/Users/carlton/bin/pycrastinate.py", line 9, in <lambda>
    return reduce(lambda results, func: enclose(func, (config, results)),
  File "/Users/carlton/Documents/pycrastinate/enclose/print_log.py", line 13, in print_log
    results = func(*params)
  File "/Users/carlton/Documents/pycrastinate/modules/process_results.py", line 7, in process_results
    deque(data, 0)
  File "/Users/carlton/Documents/pycrastinate/modules/save_to_file.py", line 12, in save_to_file
    for d in data:
  File "/Users/carlton/Documents/pycrastinate/modules/print_summary.py", line 2, in print_summary
    report = "\n".join(data)
  File "/Users/carlton/Documents/pycrastinate/modules/text_summary.py", line 20, in <genexpr>
    repeat(el, 1) if isinstance(el, str)
  File "/Users/carlton/Documents/pycrastinate/modules/text_summary.py", line 13, in nested_report
    str_attrs = [str(el) for el in (line[attr] for attr in col_order)]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-31: ordinal not in range(128)
```

So I switched to Python 3 — which runs ok but writes byte strings to the report file:

```
$ cat report.txt 
================================================================================
token > date > email > line_count > file_path > code
Generated at: 2015-07-16 11:27:31.191042
================================================================================
b'TODO'
  b'./MY_FILE.PY'
      ...
```

(Again, happy to have a look at this but wanted to get it down.)

**Comment by isaacbernat** [comment]
Good catch! It looks like the classic python2 ascii encode error when trying to cast a non-ascii strings (`str(el)` in this case). If I was only supporting python2 I could probably get away with just replacing `str` with `unicode` and maybe checking both types instead of just `str` `isinstance(el, str)`.

Could you try adding a unicode string prefix on all strings variables on this file (e.g. line 18 to be `[u"{}{}".format(ind, key)],` instead of `["{}{}".format(ind, key)],`) and see if it works? Alternatively, can you give me an example/test case where it breaks so I can figure what's wrong myself?

Thanks!

**Comment by carltongibson** [comment]
> Could you try adding a unicode string prefix...

Alas not quite so easy; we just move the error...

```
  ...
  File "/Users/carlton/Documents/pycrastinate/modules/text_summary.py", line 13, in nested_report
    str_attrs = [str(el) for el in (line[attr] for attr in col_order)]
UnicodeEncodeError: 'ascii' codec can't encode characters in position 30-31: ordinal not in range(128)
```

I'll have a play and see if I can pin it down, at least with a good test case. (It'll give me a chance to rummage through the package anyway.)

**Comment by carltongibson** [comment]
Hi @isaacbernat. Sorry for the slow follow-up. 

I was playing with this now. I went through and threw in `from __future__ import unicode_literals`s all over the place, with no change. 

The error is coming up in `text_summay.nested_report` (on line 16) where `str` is being called. I switch in `unicode` here and the report runs. 

I then get the weird result that the report is almost all printed in a single column (Top section pasted below)

Is the solution here just to run with Python 3? (No problem with that if so) Or does this make sense to you, as the author?

Thanks! 


```
================================================================================
t
o
k
e
n
 
>
 
d
a
t
e
 
>
 
e
m
a
i
l
 
>
 
l
i
n
e
_
c
o
u
n
t
 
>
 
f
i
l
e
_
p
a
t
h
 
>
 
c
o
d
e


G
e
n
e
r
a
t
e
d
 
a
t
:
 
2
0
1
5
-
0
8
-
2
2
 
2
1
:
0
2
:
0
8
.
8
6
3
5
0
8
================================================================================
TODO
  ./PYCRASTINATE/CONFIG.PY
 
```

**Comment by isaacbernat** [comment]
Hi, thanks for getting back on with this error @carltongibson.

Looking at the output you pasted, it seems the code (somewhere) is expecting a list (of strings/unicodes/etc.) but instead getting a single string. Then those single strings are iterated one by one, and a character is received where a string would be expected.

If that's the case, [text_summary](https://github.com/isaacbernat/pycrastinate/blob/master/modules/text_summary.py) line 8 (my line numbers are different than yours, as you added some code modifications) `if isinstance(data, list):` should take care of this, but maybe there is a missing or a wrong check somewhere else. 

Could it be that when you change `repeat(el, 1) if isinstance(el, str)` to unicode there are still some str somewhere and the code gets messed up? Can you try with `repeat(el, 1) if isinstance(el, str) or isinstance(el, unicode)`.

If you give me an example case I can reproduce the error I may be able to give you more details.

I don't think using Python 3 is the solution, but it looks like is a valid workaround for your case, and if that works for you, maybe that's good enough (I would definitely prefer the code to work as intended in Python 2 and 3, it would solve this problem in the future for more people).
